// ─── Role Access Hook ────────────────────────────────────────────────────────
// Provides role-based access helpers for conditional rendering and gating.

/**
 * Page keys accessible per role. Entries not listed are admin-only by default.
 * Use canAccess(pageKey) for gating, or hasAnyRole([...]) for component-level.
 */
const ROLE_PAGE_ACCESS: Record<string, string[]> = {
  admin: ["*"], // Admin can access everything
  student: [
    "dashboard",
    "courses",
    "results",
    "fees",
    "assignments",
    "exams",
    "notices",
    "registration",
    "timetable",
    "attendance",
    "documents",
    "hostel",
    "library",
    "profile",
    "academic-calendar",
    "exam-schedule",
    "announcements",
    "result-slip",
    "gpa-summary",
    "academic-status-student",
    "graduation-status",
    "course-materials",
    "course-history",
    "payment-history",
    "progression",
    "academic-transcript",
    "academic-record",
    "disciplinary-record",
    "reg-status",
    "fee-payment",
    "fee-clearance",
    "transcript-request",
    "scholarship-application",
    "department-transfer",
    "deferment",
    "course-catalog",
    "announcements-view",
    "communication-center",
    "login-activity",
    "my-certificates",
    "graduation-tracker",
    "distance-learning",
    "part-time-studies",
    "elearning",
    "student-profile",
    "my-profile",
  ],
  lecturer: [
    "dashboard",
    "courses",
    "results",
    "assignments",
    "cbt",
    "students",
    "memos",
    "timetable",
    "attendance-mgmt",
    "academic-calendar",
    "exam-schedule-lecturer",
    "ca-entry",
    "result-entry",
    "result-approval-lecturer",
    "appraisal-self",
    "combined-results",
    "student-records",
    "score-bulk-upload",
    "combination-score-sheet",
    "handwriting-scanner",
    "training-application",
    "staff-directory",
    "course-catalog",
    "announcement-view",
    "communication-center",
    "certificate-courses",
    "elearning-lecturer",
    "attendance-analytics",
    "cbt-analytics-lecturer",
    "staff-profile",
    "login-activity",
    "my-profile",
  ],
  hod: [
    "dashboard",
    "result-approval-hod",
    "hod-students",
    "academic-calendar",
    "dept-analytics",
    "dept-results",
    "student-records",
    "pass-fail-lists",
    "result-entry-review",
    "score-sheet-results",
    "appraisal-review",
    "complaints-hod",
    "staff-directory",
    "training-approval-hod",
    "disciplinary-records",
    "memos",
    "budget-request",
    "course-catalog",
    "communication-center",
    "announcement-view",
    "curriculum-management",
    "certificate-courses",
    "graduation-tracker",
    "student-profiles",
    "promotion-results",
    "staff-profile",
    "login-activity",
    "my-profile",
  ],
  bursary: [
    "dashboard",
    "invoices",
    "payments",
    "students",
    "reports",
    "receipts",
    "reconciliation",
    "student-records",
    "debt-aging",
    "installment-plans",
    "fee-waivers",
    "bursary-reconciliation",
    "fee-structure",
    "communication-center",
    "staff-profile",
    "login-activity",
    "my-profile",
  ],
  hr: [
    "dashboard",
    "staff",
    "leaves",
    "attendance",
    "reports",
    "requests",
    "payroll",
    "appraisals",
    "student-records",
    "staff-training",
    "training-approval-hr",
    "staff-directory",
    "memos",
    "staff-onboarding",
    "staff-welfare",
    "communication-center",
    "student-profiles",
    "staff-profile",
    "login-activity",
    "my-profile",
  ],
  alumni: [
    "dashboard",
    "directory",
    "jobs",
    "events",
    "profile",
    "login-activity",
    "my-profile",
  ],
  parent: [
    "dashboard",
    "ward",
    "link-ward",
    "announcements",
    "login-activity",
    "my-profile",
  ],
};

/** Current user role (read from localStorage via a shared key). */
export function useRoleAccess(role: string) {
  function hasRole(r: string): boolean {
    return role === r;
  }

  function hasAnyRole(roles: string[]): boolean {
    return roles.includes(role);
  }

  function canAccess(pageKey: string): boolean {
    if (role === "admin") return true;
    const allowed = ROLE_PAGE_ACCESS[role] ?? [];
    return allowed.includes(pageKey) || allowed.includes("*");
  }

  return { role, hasRole, hasAnyRole, canAccess };
}
