/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicProgression {
  'stages' : Array<ProgressionStage>,
  'studentMatric' : string,
}
export interface AlumniProfile {
  'linkedIn' : string,
  'matricNumber' : string,
  'name' : string,
  'graduationYear' : bigint,
  'email' : string,
  'employer' : string,
  'jobTitle' : string,
  'department' : string,
  'location' : string,
}
export type AppraisalCycle = { 'annual' : null } |
  { 'midYear' : null };
export type AppraisalStatus = { 'submitted' : null } |
  { 'finalized' : null } |
  { 'reviewed' : null } |
  { 'draft' : null };
export type ApprovalStage = { 'vc' : null } |
  { 'dvc' : null } |
  { 'hod' : null } |
  { 'dean' : null };
export interface Assignment {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'description' : string,
  'createdByLecturerId' : string,
  'courseCode' : string,
}
export interface Course {
  'title' : string,
  'semester' : string,
  'code' : string,
  'creditUnits' : bigint,
  'department' : string,
  'lecturerId' : string,
}
export type Designation = { 'hr' : null } |
  { 'admin' : null } |
  { 'lecturer' : null } |
  { 'support' : null } |
  { 'bursary' : null };
export interface Invoice {
  'id' : string,
  'status' : InvoiceStatus,
  'semester' : string,
  'studentMatric' : string,
  'amount' : bigint,
  'paidAt' : [] | [bigint],
}
export type InvoiceStatus = { 'pending' : null } |
  { 'paid' : null };
export interface Memo {
  'title' : string,
  'body' : string,
  'createdAt' : bigint,
  'targetAudience' : string,
  'senderName' : string,
}
export interface ProgressionStage {
  'status' : string,
  'completedAt' : bigint,
  'details' : string,
  'stageName' : string,
}
export type RequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type RequestType = { 'travel' : null } |
  { 'leave' : null } |
  { 'training' : null };
export interface StaffAppraisal {
  'id' : string,
  'status' : AppraisalStatus,
  'staffName' : string,
  'period' : string,
  'kpis' : string,
  'cycle' : AppraisalCycle,
  'submittedAt' : bigint,
  'reviewComment' : [] | [string],
  'reviewerName' : string,
  'achievements' : string,
  'selfAppraisalText' : string,
  'targetsNextPeriod' : string,
  'staffPrincipal' : Principal,
  'department' : string,
  'reviewScore' : [] | [string],
}
export interface StaffProfile {
  'staffId' : string,
  'name' : string,
  'designation' : Designation,
  'email' : string,
  'department' : string,
}
export interface StaffRequest {
  'id' : string,
  'status' : RequestStatus,
  'submittedByName' : string,
  'createdAt' : bigint,
  'submittedBy' : Principal,
  'description' : string,
  'stageHistory' : Array<StageRecord>,
  'currentStage' : ApprovalStage,
  'requestType' : RequestType,
}
export interface StageRecord {
  'decision' : string,
  'comment' : string,
  'stage' : string,
  'decidedAt' : bigint,
  'decidedBy' : string,
}
export interface StudentProfile {
  'matricNumber' : string,
  'name' : string,
  'email' : string,
  'level' : string,
  'department' : string,
}
export interface Submission {
  'id' : string,
  'studentPrincipal' : string,
  'submittedAt' : bigint,
  'feedback' : [] | [string],
  'grade' : [] | [string],
  'assignmentId' : string,
  'studentMatric' : string,
  'fileIds' : Array<string>,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProgressionStage' : ActorMethod<[string, ProgressionStage], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlumniProfile' : ActorMethod<[AlumniProfile], undefined>,
  'createAssignment' : ActorMethod<[Assignment], string>,
  'createCourse' : ActorMethod<[Course], undefined>,
  'createInvoice' : ActorMethod<[Invoice], string>,
  'createMemo' : ActorMethod<[Memo], string>,
  'createProgressionRecord' : ActorMethod<[string], undefined>,
  'createStaff' : ActorMethod<[StaffProfile], undefined>,
  'createStudent' : ActorMethod<[StudentProfile], undefined>,
  'finalizeAppraisal' : ActorMethod<[string], undefined>,
  'getAlumniProfile' : ActorMethod<[string], [] | [AlumniProfile]>,
  'getAppraisal' : ActorMethod<[string], [] | [StaffAppraisal]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[string], [] | [Course]>,
  'getMemo' : ActorMethod<[string], [] | [Memo]>,
  'getProgressionRecord' : ActorMethod<[string], [] | [AcademicProgression]>,
  'getStaff' : ActorMethod<[string], [] | [StaffProfile]>,
  'getStaffRequest' : ActorMethod<[string], [] | [StaffRequest]>,
  'getStudentByEmail' : ActorMethod<[string], [] | [StudentProfile]>,
  'getStudentByMatricNumber' : ActorMethod<[string], [] | [StudentProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'gradeSubmission' : ActorMethod<[string, string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllAlumni' : ActorMethod<[], Array<AlumniProfile>>,
  'listAllAppraisals' : ActorMethod<[], Array<StaffAppraisal>>,
  'listAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'listAllCourses' : ActorMethod<[], Array<Course>>,
  'listAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'listAllMemos' : ActorMethod<[], Array<Memo>>,
  'listAllProgressionRecords' : ActorMethod<[], Array<AcademicProgression>>,
  'listAllStaff' : ActorMethod<[], Array<StaffProfile>>,
  'listAllStaffByStaffId' : ActorMethod<[], Array<StaffProfile>>,
  'listAllStaffRequests' : ActorMethod<[], Array<StaffRequest>>,
  'listAllStudents' : ActorMethod<[], Array<StudentProfile>>,
  'listAllStudentsByMatricNumber' : ActorMethod<[], Array<StudentProfile>>,
  'listAppraisalsByStaff' : ActorMethod<[Principal], Array<StaffAppraisal>>,
  'listAssignmentsByCourse' : ActorMethod<[string], Array<Assignment>>,
  'listInvoicesByStudent' : ActorMethod<[string], Array<Invoice>>,
  'listMyStaffRequests' : ActorMethod<[], Array<StaffRequest>>,
  'listMySubmissions' : ActorMethod<[string], Array<Submission>>,
  'listSubmissionsByAssignment' : ActorMethod<[string], Array<Submission>>,
  'markInvoicePaid' : ActorMethod<[string, bigint], undefined>,
  'processStaffRequest' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'reviewAppraisal' : ActorMethod<[string, string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAssignment' : ActorMethod<[Submission], string>,
  'submitSelfAppraisal' : ActorMethod<[StaffAppraisal], string>,
  'submitStaffRequest' : ActorMethod<[StaffRequest], string>,
  'updateAlumniProfile' : ActorMethod<[string, AlumniProfile], undefined>,
  'updateCourse' : ActorMethod<[string, Course], undefined>,
  'updateStaff' : ActorMethod<[string, StaffProfile], undefined>,
  'updateStudent' : ActorMethod<[string, StudentProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];