/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProgressionStage = IDL.Record({
  'status' : IDL.Text,
  'completedAt' : IDL.Int,
  'details' : IDL.Text,
  'stageName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlumniProfile = IDL.Record({
  'linkedIn' : IDL.Text,
  'matricNumber' : IDL.Text,
  'name' : IDL.Text,
  'graduationYear' : IDL.Nat,
  'email' : IDL.Text,
  'employer' : IDL.Text,
  'jobTitle' : IDL.Text,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const Assignment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'createdByLecturerId' : IDL.Text,
  'courseCode' : IDL.Text,
});
export const Course = IDL.Record({
  'title' : IDL.Text,
  'semester' : IDL.Text,
  'code' : IDL.Text,
  'creditUnits' : IDL.Nat,
  'department' : IDL.Text,
  'lecturerId' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : InvoiceStatus,
  'semester' : IDL.Text,
  'studentMatric' : IDL.Text,
  'amount' : IDL.Nat,
  'paidAt' : IDL.Opt(IDL.Int),
});
export const Memo = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'targetAudience' : IDL.Text,
  'senderName' : IDL.Text,
});
export const Designation = IDL.Variant({
  'hr' : IDL.Null,
  'admin' : IDL.Null,
  'lecturer' : IDL.Null,
  'support' : IDL.Null,
  'bursary' : IDL.Null,
});
export const StaffProfile = IDL.Record({
  'staffId' : IDL.Text,
  'name' : IDL.Text,
  'designation' : Designation,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'matricNumber' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'level' : IDL.Text,
  'department' : IDL.Text,
});
export const AppraisalStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'finalized' : IDL.Null,
  'reviewed' : IDL.Null,
  'draft' : IDL.Null,
});
export const AppraisalCycle = IDL.Variant({
  'annual' : IDL.Null,
  'midYear' : IDL.Null,
});
export const StaffAppraisal = IDL.Record({
  'id' : IDL.Text,
  'status' : AppraisalStatus,
  'staffName' : IDL.Text,
  'period' : IDL.Text,
  'kpis' : IDL.Text,
  'cycle' : AppraisalCycle,
  'submittedAt' : IDL.Int,
  'reviewComment' : IDL.Opt(IDL.Text),
  'reviewerName' : IDL.Text,
  'achievements' : IDL.Text,
  'selfAppraisalText' : IDL.Text,
  'targetsNextPeriod' : IDL.Text,
  'staffPrincipal' : IDL.Principal,
  'department' : IDL.Text,
  'reviewScore' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const AcademicProgression = IDL.Record({
  'stages' : IDL.Vec(ProgressionStage),
  'studentMatric' : IDL.Text,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const StageRecord = IDL.Record({
  'decision' : IDL.Text,
  'comment' : IDL.Text,
  'stage' : IDL.Text,
  'decidedAt' : IDL.Int,
  'decidedBy' : IDL.Text,
});
export const ApprovalStage = IDL.Variant({
  'vc' : IDL.Null,
  'dvc' : IDL.Null,
  'hod' : IDL.Null,
  'dean' : IDL.Null,
});
export const RequestType = IDL.Variant({
  'travel' : IDL.Null,
  'leave' : IDL.Null,
  'training' : IDL.Null,
});
export const StaffRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'submittedByName' : IDL.Text,
  'createdAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'stageHistory' : IDL.Vec(StageRecord),
  'currentStage' : ApprovalStage,
  'requestType' : RequestType,
});
export const Submission = IDL.Record({
  'id' : IDL.Text,
  'studentPrincipal' : IDL.Text,
  'submittedAt' : IDL.Int,
  'feedback' : IDL.Opt(IDL.Text),
  'grade' : IDL.Opt(IDL.Text),
  'assignmentId' : IDL.Text,
  'studentMatric' : IDL.Text,
  'fileIds' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProgressionStage' : IDL.Func([IDL.Text, ProgressionStage], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlumniProfile' : IDL.Func([AlumniProfile], [], []),
  'createAssignment' : IDL.Func([Assignment], [IDL.Text], []),
  'createCourse' : IDL.Func([Course], [], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Text], []),
  'createMemo' : IDL.Func([Memo], [IDL.Text], []),
  'createProgressionRecord' : IDL.Func([IDL.Text], [], []),
  'createStaff' : IDL.Func([StaffProfile], [], []),
  'createStudent' : IDL.Func([StudentProfile], [], []),
  'finalizeAppraisal' : IDL.Func([IDL.Text], [], []),
  'getAlumniProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AlumniProfile)],
      ['query'],
    ),
  'getAppraisal' : IDL.Func([IDL.Text], [IDL.Opt(StaffAppraisal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
  'getMemo' : IDL.Func([IDL.Text], [IDL.Opt(Memo)], ['query']),
  'getProgressionRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AcademicProgression)],
      ['query'],
    ),
  'getStaff' : IDL.Func([IDL.Text], [IDL.Opt(StaffProfile)], ['query']),
  'getStaffRequest' : IDL.Func([IDL.Text], [IDL.Opt(StaffRequest)], ['query']),
  'getStudentByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getStudentByMatricNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'gradeSubmission' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAlumni' : IDL.Func([], [IDL.Vec(AlumniProfile)], ['query']),
  'listAllAppraisals' : IDL.Func([], [IDL.Vec(StaffAppraisal)], ['query']),
  'listAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'listAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'listAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listAllMemos' : IDL.Func([], [IDL.Vec(Memo)], ['query']),
  'listAllProgressionRecords' : IDL.Func(
      [],
      [IDL.Vec(AcademicProgression)],
      ['query'],
    ),
  'listAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'listAllStaffByStaffId' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'listAllStaffRequests' : IDL.Func([], [IDL.Vec(StaffRequest)], ['query']),
  'listAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'listAllStudentsByMatricNumber' : IDL.Func(
      [],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'listAppraisalsByStaff' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StaffAppraisal)],
      ['query'],
    ),
  'listAssignmentsByCourse' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'listInvoicesByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
  'listMyStaffRequests' : IDL.Func([], [IDL.Vec(StaffRequest)], ['query']),
  'listMySubmissions' : IDL.Func([IDL.Text], [IDL.Vec(Submission)], ['query']),
  'listSubmissionsByAssignment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'markInvoicePaid' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'processStaffRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'reviewAppraisal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssignment' : IDL.Func([Submission], [IDL.Text], []),
  'submitSelfAppraisal' : IDL.Func([StaffAppraisal], [IDL.Text], []),
  'submitStaffRequest' : IDL.Func([StaffRequest], [IDL.Text], []),
  'updateAlumniProfile' : IDL.Func([IDL.Text, AlumniProfile], [], []),
  'updateCourse' : IDL.Func([IDL.Text, Course], [], []),
  'updateStaff' : IDL.Func([IDL.Text, StaffProfile], [], []),
  'updateStudent' : IDL.Func([IDL.Text, StudentProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProgressionStage = IDL.Record({
    'status' : IDL.Text,
    'completedAt' : IDL.Int,
    'details' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlumniProfile = IDL.Record({
    'linkedIn' : IDL.Text,
    'matricNumber' : IDL.Text,
    'name' : IDL.Text,
    'graduationYear' : IDL.Nat,
    'email' : IDL.Text,
    'employer' : IDL.Text,
    'jobTitle' : IDL.Text,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'createdByLecturerId' : IDL.Text,
    'courseCode' : IDL.Text,
  });
  const Course = IDL.Record({
    'title' : IDL.Text,
    'semester' : IDL.Text,
    'code' : IDL.Text,
    'creditUnits' : IDL.Nat,
    'department' : IDL.Text,
    'lecturerId' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : InvoiceStatus,
    'semester' : IDL.Text,
    'studentMatric' : IDL.Text,
    'amount' : IDL.Nat,
    'paidAt' : IDL.Opt(IDL.Int),
  });
  const Memo = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'targetAudience' : IDL.Text,
    'senderName' : IDL.Text,
  });
  const Designation = IDL.Variant({
    'hr' : IDL.Null,
    'admin' : IDL.Null,
    'lecturer' : IDL.Null,
    'support' : IDL.Null,
    'bursary' : IDL.Null,
  });
  const StaffProfile = IDL.Record({
    'staffId' : IDL.Text,
    'name' : IDL.Text,
    'designation' : Designation,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'matricNumber' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'level' : IDL.Text,
    'department' : IDL.Text,
  });
  const AppraisalStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'finalized' : IDL.Null,
    'reviewed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const AppraisalCycle = IDL.Variant({
    'annual' : IDL.Null,
    'midYear' : IDL.Null,
  });
  const StaffAppraisal = IDL.Record({
    'id' : IDL.Text,
    'status' : AppraisalStatus,
    'staffName' : IDL.Text,
    'period' : IDL.Text,
    'kpis' : IDL.Text,
    'cycle' : AppraisalCycle,
    'submittedAt' : IDL.Int,
    'reviewComment' : IDL.Opt(IDL.Text),
    'reviewerName' : IDL.Text,
    'achievements' : IDL.Text,
    'selfAppraisalText' : IDL.Text,
    'targetsNextPeriod' : IDL.Text,
    'staffPrincipal' : IDL.Principal,
    'department' : IDL.Text,
    'reviewScore' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const AcademicProgression = IDL.Record({
    'stages' : IDL.Vec(ProgressionStage),
    'studentMatric' : IDL.Text,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const StageRecord = IDL.Record({
    'decision' : IDL.Text,
    'comment' : IDL.Text,
    'stage' : IDL.Text,
    'decidedAt' : IDL.Int,
    'decidedBy' : IDL.Text,
  });
  const ApprovalStage = IDL.Variant({
    'vc' : IDL.Null,
    'dvc' : IDL.Null,
    'hod' : IDL.Null,
    'dean' : IDL.Null,
  });
  const RequestType = IDL.Variant({
    'travel' : IDL.Null,
    'leave' : IDL.Null,
    'training' : IDL.Null,
  });
  const StaffRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'submittedByName' : IDL.Text,
    'createdAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'stageHistory' : IDL.Vec(StageRecord),
    'currentStage' : ApprovalStage,
    'requestType' : RequestType,
  });
  const Submission = IDL.Record({
    'id' : IDL.Text,
    'studentPrincipal' : IDL.Text,
    'submittedAt' : IDL.Int,
    'feedback' : IDL.Opt(IDL.Text),
    'grade' : IDL.Opt(IDL.Text),
    'assignmentId' : IDL.Text,
    'studentMatric' : IDL.Text,
    'fileIds' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProgressionStage' : IDL.Func([IDL.Text, ProgressionStage], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlumniProfile' : IDL.Func([AlumniProfile], [], []),
    'createAssignment' : IDL.Func([Assignment], [IDL.Text], []),
    'createCourse' : IDL.Func([Course], [], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Text], []),
    'createMemo' : IDL.Func([Memo], [IDL.Text], []),
    'createProgressionRecord' : IDL.Func([IDL.Text], [], []),
    'createStaff' : IDL.Func([StaffProfile], [], []),
    'createStudent' : IDL.Func([StudentProfile], [], []),
    'finalizeAppraisal' : IDL.Func([IDL.Text], [], []),
    'getAlumniProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AlumniProfile)],
        ['query'],
      ),
    'getAppraisal' : IDL.Func([IDL.Text], [IDL.Opt(StaffAppraisal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
    'getMemo' : IDL.Func([IDL.Text], [IDL.Opt(Memo)], ['query']),
    'getProgressionRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AcademicProgression)],
        ['query'],
      ),
    'getStaff' : IDL.Func([IDL.Text], [IDL.Opt(StaffProfile)], ['query']),
    'getStaffRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StaffRequest)],
        ['query'],
      ),
    'getStudentByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getStudentByMatricNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'gradeSubmission' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAlumni' : IDL.Func([], [IDL.Vec(AlumniProfile)], ['query']),
    'listAllAppraisals' : IDL.Func([], [IDL.Vec(StaffAppraisal)], ['query']),
    'listAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'listAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'listAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listAllMemos' : IDL.Func([], [IDL.Vec(Memo)], ['query']),
    'listAllProgressionRecords' : IDL.Func(
        [],
        [IDL.Vec(AcademicProgression)],
        ['query'],
      ),
    'listAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'listAllStaffByStaffId' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'listAllStaffRequests' : IDL.Func([], [IDL.Vec(StaffRequest)], ['query']),
    'listAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'listAllStudentsByMatricNumber' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'listAppraisalsByStaff' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StaffAppraisal)],
        ['query'],
      ),
    'listAssignmentsByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'listInvoicesByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'listMyStaffRequests' : IDL.Func([], [IDL.Vec(StaffRequest)], ['query']),
    'listMySubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'listSubmissionsByAssignment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'markInvoicePaid' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'processStaffRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'reviewAppraisal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssignment' : IDL.Func([Submission], [IDL.Text], []),
    'submitSelfAppraisal' : IDL.Func([StaffAppraisal], [IDL.Text], []),
    'submitStaffRequest' : IDL.Func([StaffRequest], [IDL.Text], []),
    'updateAlumniProfile' : IDL.Func([IDL.Text, AlumniProfile], [], []),
    'updateCourse' : IDL.Func([IDL.Text, Course], [], []),
    'updateStaff' : IDL.Func([IDL.Text, StaffProfile], [], []),
    'updateStudent' : IDL.Func([IDL.Text, StudentProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };