/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProgressionStage = IDL.Record({
  'status' : IDL.Text,
  'completedAt' : IDL.Int,
  'details' : IDL.Text,
  'stageName' : IDL.Text,
});
export const HostelApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'studentName' : IDL.Text,
  'level' : IDL.Text,
  'processedAt' : IDL.Int,
  'preferredBlock' : IDL.Text,
  'adminComment' : IDL.Text,
  'studentMatric' : IDL.Text,
  'assignedRoom' : IDL.Text,
  'department' : IDL.Text,
  'roomType' : IDL.Text,
  'applicationDate' : IDL.Int,
  'specialNeeds' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlumniProfile = IDL.Record({
  'linkedIn' : IDL.Text,
  'matricNumber' : IDL.Text,
  'name' : IDL.Text,
  'graduationYear' : IDL.Nat,
  'email' : IDL.Text,
  'employer' : IDL.Text,
  'jobTitle' : IDL.Text,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'expiresAt' : IDL.Int,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'isActive' : IDL.Bool,
  'targetRoles' : IDL.Vec(IDL.Text),
  'priority' : IDL.Text,
});
export const Assignment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'createdByLecturerId' : IDL.Text,
  'courseCode' : IDL.Text,
});
export const CAScore = IDL.Record({
  'id' : IDL.Text,
  'semester' : IDL.Text,
  'quizScore' : IDL.Nat,
  'testScore' : IDL.Nat,
  'totalCA' : IDL.Nat,
  'createdAt' : IDL.Int,
  'assignmentScore' : IDL.Nat,
  'lecturerName' : IDL.Text,
  'session' : IDL.Text,
  'attendanceScore' : IDL.Nat,
  'studentMatric' : IDL.Text,
  'courseCode' : IDL.Text,
});
export const Course = IDL.Record({
  'title' : IDL.Text,
  'semester' : IDL.Text,
  'code' : IDL.Text,
  'creditUnits' : IDL.Nat,
  'department' : IDL.Text,
  'lecturerId' : IDL.Text,
});
export const DocumentRecord = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'documentType' : IDL.Text,
  'uploaderName' : IDL.Text,
  'uploaderPrincipal' : IDL.Text,
  'linkedRecordType' : IDL.Text,
  'notes' : IDL.Text,
  'linkedRecordId' : IDL.Text,
  'blobId' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const ExamResult = IDL.Record({
  'id' : IDL.Text,
  'remark' : IDL.Text,
  'status' : IDL.Text,
  'semester' : IDL.Text,
  'createdAt' : IDL.Int,
  'rejectionReason' : IDL.Text,
  'gradePoints' : IDL.Nat,
  'examScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'session' : IDL.Text,
  'grade' : IDL.Text,
  'creditUnits' : IDL.Nat,
  'studentMatric' : IDL.Text,
  'courseTitle' : IDL.Text,
  'courseCode' : IDL.Text,
  'caScore' : IDL.Nat,
  'approvalLevel' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : InvoiceStatus,
  'semester' : IDL.Text,
  'studentMatric' : IDL.Text,
  'amount' : IDL.Nat,
  'paidAt' : IDL.Opt(IDL.Int),
});
export const Memo = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'targetAudience' : IDL.Text,
  'senderName' : IDL.Text,
});
export const Designation = IDL.Variant({
  'hr' : IDL.Null,
  'admin' : IDL.Null,
  'lecturer' : IDL.Null,
  'support' : IDL.Null,
  'bursary' : IDL.Null,
});
export const StaffProfile = IDL.Record({
  'staffId' : IDL.Text,
  'name' : IDL.Text,
  'designation' : Designation,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'matricNumber' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'level' : IDL.Text,
  'department' : IDL.Text,
});
export const CourseRegistration = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'semester' : IDL.Text,
  'session' : IDL.Text,
  'creditUnits' : IDL.Nat,
  'studentMatric' : IDL.Text,
  'courseTitle' : IDL.Text,
  'courseCode' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const AppraisalStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'finalized' : IDL.Null,
  'reviewed' : IDL.Null,
  'draft' : IDL.Null,
});
export const AppraisalCycle = IDL.Variant({
  'annual' : IDL.Null,
  'midYear' : IDL.Null,
});
export const StaffAppraisal = IDL.Record({
  'id' : IDL.Text,
  'status' : AppraisalStatus,
  'staffName' : IDL.Text,
  'period' : IDL.Text,
  'kpis' : IDL.Text,
  'cycle' : AppraisalCycle,
  'submittedAt' : IDL.Int,
  'reviewComment' : IDL.Opt(IDL.Text),
  'reviewerName' : IDL.Text,
  'achievements' : IDL.Text,
  'selfAppraisalText' : IDL.Text,
  'targetsNextPeriod' : IDL.Text,
  'staffPrincipal' : IDL.Principal,
  'department' : IDL.Text,
  'reviewScore' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const AcademicProgression = IDL.Record({
  'stages' : IDL.Vec(ProgressionStage),
  'studentMatric' : IDL.Text,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const StageRecord = IDL.Record({
  'decision' : IDL.Text,
  'comment' : IDL.Text,
  'stage' : IDL.Text,
  'decidedAt' : IDL.Int,
  'decidedBy' : IDL.Text,
});
export const ApprovalStage = IDL.Variant({
  'vc' : IDL.Null,
  'dvc' : IDL.Null,
  'hod' : IDL.Null,
  'dean' : IDL.Null,
});
export const RequestType = IDL.Variant({
  'travel' : IDL.Null,
  'leave' : IDL.Null,
  'training' : IDL.Null,
});
export const StaffRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'submittedByName' : IDL.Text,
  'createdAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'stageHistory' : IDL.Vec(StageRecord),
  'currentStage' : ApprovalStage,
  'requestType' : RequestType,
});
export const Submission = IDL.Record({
  'id' : IDL.Text,
  'studentPrincipal' : IDL.Text,
  'submittedAt' : IDL.Int,
  'feedback' : IDL.Opt(IDL.Text),
  'grade' : IDL.Opt(IDL.Text),
  'assignmentId' : IDL.Text,
  'studentMatric' : IDL.Text,
  'fileIds' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProgressionStage' : IDL.Func([IDL.Text, ProgressionStage], [], []),
  'applyForHostel' : IDL.Func([HostelApplication], [IDL.Text], []),
  'approveRegistration' : IDL.Func([IDL.Text], [], []),
  'approveResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlumniProfile' : IDL.Func([AlumniProfile], [], []),
  'createAnnouncement' : IDL.Func([Announcement], [IDL.Text], []),
  'createAssignment' : IDL.Func([Assignment], [IDL.Text], []),
  'createCAScore' : IDL.Func([CAScore], [IDL.Text], []),
  'createCourse' : IDL.Func([Course], [], []),
  'createDocumentRecord' : IDL.Func([DocumentRecord], [IDL.Text], []),
  'createExamResult' : IDL.Func([ExamResult], [IDL.Text], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Text], []),
  'createMemo' : IDL.Func([Memo], [IDL.Text], []),
  'createProgressionRecord' : IDL.Func([IDL.Text], [], []),
  'createStaff' : IDL.Func([StaffProfile], [], []),
  'createStudent' : IDL.Func([StudentProfile], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
  'dropCourse' : IDL.Func([IDL.Text], [], []),
  'finalizeAppraisal' : IDL.Func([IDL.Text], [], []),
  'getAllRegistrations' : IDL.Func(
      [],
      [IDL.Vec(CourseRegistration)],
      ['query'],
    ),
  'getAlumniProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AlumniProfile)],
      ['query'],
    ),
  'getAnnouncement' : IDL.Func([IDL.Text], [IDL.Opt(Announcement)], ['query']),
  'getAppraisal' : IDL.Func([IDL.Text], [IDL.Opt(StaffAppraisal)], ['query']),
  'getCAScore' : IDL.Func([IDL.Text], [IDL.Opt(CAScore)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
  'getDocumentRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DocumentRecord)],
      ['query'],
    ),
  'getExamResult' : IDL.Func([IDL.Text], [IDL.Opt(ExamResult)], ['query']),
  'getHostelApplication' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HostelApplication)],
      ['query'],
    ),
  'getMemo' : IDL.Func([IDL.Text], [IDL.Opt(Memo)], ['query']),
  'getProgressionRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AcademicProgression)],
      ['query'],
    ),
  'getStaff' : IDL.Func([IDL.Text], [IDL.Opt(StaffProfile)], ['query']),
  'getStaffRequest' : IDL.Func([IDL.Text], [IDL.Opt(StaffRequest)], ['query']),
  'getStudentByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getStudentByMatricNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'gradeSubmission' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listAllAlumni' : IDL.Func([], [IDL.Vec(AlumniProfile)], ['query']),
  'listAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listAllAppraisals' : IDL.Func([], [IDL.Vec(StaffAppraisal)], ['query']),
  'listAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'listAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'listAllDocuments' : IDL.Func([], [IDL.Vec(DocumentRecord)], ['query']),
  'listAllHostelApplications' : IDL.Func(
      [],
      [IDL.Vec(HostelApplication)],
      ['query'],
    ),
  'listAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listAllMemos' : IDL.Func([], [IDL.Vec(Memo)], ['query']),
  'listAllProgressionRecords' : IDL.Func(
      [],
      [IDL.Vec(AcademicProgression)],
      ['query'],
    ),
  'listAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'listAllStaffByStaffId' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'listAllStaffRequests' : IDL.Func([], [IDL.Vec(StaffRequest)], ['query']),
  'listAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'listAllStudentsByMatricNumber' : IDL.Func(
      [],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'listAppraisalsByStaff' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StaffAppraisal)],
      ['query'],
    ),
  'listAssignmentsByCourse' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'listCAScoresByCourse' : IDL.Func([IDL.Text], [IDL.Vec(CAScore)], ['query']),
  'listCAScoresByStudent' : IDL.Func([IDL.Text], [IDL.Vec(CAScore)], ['query']),
  'listDocumentsByLinkedRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DocumentRecord)],
      ['query'],
    ),
  'listDocumentsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DocumentRecord)],
      ['query'],
    ),
  'listDocumentsByUploader' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DocumentRecord)],
      ['query'],
    ),
  'listHostelApplicationsByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HostelApplication)],
      ['query'],
    ),
  'listHostelApplicationsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HostelApplication)],
      ['query'],
    ),
  'listInvoicesByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
  'listMyStaffRequests' : IDL.Func([], [IDL.Vec(StaffRequest)], ['query']),
  'listMySubmissions' : IDL.Func([IDL.Text], [IDL.Vec(Submission)], ['query']),
  'listRegistrationsByCourse' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CourseRegistration)],
      ['query'],
    ),
  'listRegistrationsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CourseRegistration)],
      ['query'],
    ),
  'listResultsByCourse' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'listResultsBySemester' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'listResultsByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'listResultsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'listSubmissionsByAssignment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'markInvoicePaid' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'processHostelApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'processStaffRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'publishResult' : IDL.Func([IDL.Text], [], []),
  'registerCourse' : IDL.Func([CourseRegistration], [IDL.Text], []),
  'rejectResult' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'reviewAppraisal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssignment' : IDL.Func([Submission], [IDL.Text], []),
  'submitResultForApproval' : IDL.Func([IDL.Text], [], []),
  'submitSelfAppraisal' : IDL.Func([StaffAppraisal], [IDL.Text], []),
  'submitStaffRequest' : IDL.Func([StaffRequest], [IDL.Text], []),
  'updateAlumniProfile' : IDL.Func([IDL.Text, AlumniProfile], [], []),
  'updateAnnouncement' : IDL.Func([IDL.Text, Announcement], [], []),
  'updateCAScore' : IDL.Func([IDL.Text, CAScore], [], []),
  'updateCourse' : IDL.Func([IDL.Text, Course], [], []),
  'updateExamResult' : IDL.Func([IDL.Text, ExamResult], [], []),
  'updateStaff' : IDL.Func([IDL.Text, StaffProfile], [], []),
  'updateStudent' : IDL.Func([IDL.Text, StudentProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProgressionStage = IDL.Record({
    'status' : IDL.Text,
    'completedAt' : IDL.Int,
    'details' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const HostelApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'studentName' : IDL.Text,
    'level' : IDL.Text,
    'processedAt' : IDL.Int,
    'preferredBlock' : IDL.Text,
    'adminComment' : IDL.Text,
    'studentMatric' : IDL.Text,
    'assignedRoom' : IDL.Text,
    'department' : IDL.Text,
    'roomType' : IDL.Text,
    'applicationDate' : IDL.Int,
    'specialNeeds' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlumniProfile = IDL.Record({
    'linkedIn' : IDL.Text,
    'matricNumber' : IDL.Text,
    'name' : IDL.Text,
    'graduationYear' : IDL.Nat,
    'email' : IDL.Text,
    'employer' : IDL.Text,
    'jobTitle' : IDL.Text,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'expiresAt' : IDL.Int,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'isActive' : IDL.Bool,
    'targetRoles' : IDL.Vec(IDL.Text),
    'priority' : IDL.Text,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'createdByLecturerId' : IDL.Text,
    'courseCode' : IDL.Text,
  });
  const CAScore = IDL.Record({
    'id' : IDL.Text,
    'semester' : IDL.Text,
    'quizScore' : IDL.Nat,
    'testScore' : IDL.Nat,
    'totalCA' : IDL.Nat,
    'createdAt' : IDL.Int,
    'assignmentScore' : IDL.Nat,
    'lecturerName' : IDL.Text,
    'session' : IDL.Text,
    'attendanceScore' : IDL.Nat,
    'studentMatric' : IDL.Text,
    'courseCode' : IDL.Text,
  });
  const Course = IDL.Record({
    'title' : IDL.Text,
    'semester' : IDL.Text,
    'code' : IDL.Text,
    'creditUnits' : IDL.Nat,
    'department' : IDL.Text,
    'lecturerId' : IDL.Text,
  });
  const DocumentRecord = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'documentType' : IDL.Text,
    'uploaderName' : IDL.Text,
    'uploaderPrincipal' : IDL.Text,
    'linkedRecordType' : IDL.Text,
    'notes' : IDL.Text,
    'linkedRecordId' : IDL.Text,
    'blobId' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const ExamResult = IDL.Record({
    'id' : IDL.Text,
    'remark' : IDL.Text,
    'status' : IDL.Text,
    'semester' : IDL.Text,
    'createdAt' : IDL.Int,
    'rejectionReason' : IDL.Text,
    'gradePoints' : IDL.Nat,
    'examScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'session' : IDL.Text,
    'grade' : IDL.Text,
    'creditUnits' : IDL.Nat,
    'studentMatric' : IDL.Text,
    'courseTitle' : IDL.Text,
    'courseCode' : IDL.Text,
    'caScore' : IDL.Nat,
    'approvalLevel' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : InvoiceStatus,
    'semester' : IDL.Text,
    'studentMatric' : IDL.Text,
    'amount' : IDL.Nat,
    'paidAt' : IDL.Opt(IDL.Int),
  });
  const Memo = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'targetAudience' : IDL.Text,
    'senderName' : IDL.Text,
  });
  const Designation = IDL.Variant({
    'hr' : IDL.Null,
    'admin' : IDL.Null,
    'lecturer' : IDL.Null,
    'support' : IDL.Null,
    'bursary' : IDL.Null,
  });
  const StaffProfile = IDL.Record({
    'staffId' : IDL.Text,
    'name' : IDL.Text,
    'designation' : Designation,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'matricNumber' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'level' : IDL.Text,
    'department' : IDL.Text,
  });
  const CourseRegistration = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'semester' : IDL.Text,
    'session' : IDL.Text,
    'creditUnits' : IDL.Nat,
    'studentMatric' : IDL.Text,
    'courseTitle' : IDL.Text,
    'courseCode' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const AppraisalStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'finalized' : IDL.Null,
    'reviewed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const AppraisalCycle = IDL.Variant({
    'annual' : IDL.Null,
    'midYear' : IDL.Null,
  });
  const StaffAppraisal = IDL.Record({
    'id' : IDL.Text,
    'status' : AppraisalStatus,
    'staffName' : IDL.Text,
    'period' : IDL.Text,
    'kpis' : IDL.Text,
    'cycle' : AppraisalCycle,
    'submittedAt' : IDL.Int,
    'reviewComment' : IDL.Opt(IDL.Text),
    'reviewerName' : IDL.Text,
    'achievements' : IDL.Text,
    'selfAppraisalText' : IDL.Text,
    'targetsNextPeriod' : IDL.Text,
    'staffPrincipal' : IDL.Principal,
    'department' : IDL.Text,
    'reviewScore' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const AcademicProgression = IDL.Record({
    'stages' : IDL.Vec(ProgressionStage),
    'studentMatric' : IDL.Text,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const StageRecord = IDL.Record({
    'decision' : IDL.Text,
    'comment' : IDL.Text,
    'stage' : IDL.Text,
    'decidedAt' : IDL.Int,
    'decidedBy' : IDL.Text,
  });
  const ApprovalStage = IDL.Variant({
    'vc' : IDL.Null,
    'dvc' : IDL.Null,
    'hod' : IDL.Null,
    'dean' : IDL.Null,
  });
  const RequestType = IDL.Variant({
    'travel' : IDL.Null,
    'leave' : IDL.Null,
    'training' : IDL.Null,
  });
  const StaffRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'submittedByName' : IDL.Text,
    'createdAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'stageHistory' : IDL.Vec(StageRecord),
    'currentStage' : ApprovalStage,
    'requestType' : RequestType,
  });
  const Submission = IDL.Record({
    'id' : IDL.Text,
    'studentPrincipal' : IDL.Text,
    'submittedAt' : IDL.Int,
    'feedback' : IDL.Opt(IDL.Text),
    'grade' : IDL.Opt(IDL.Text),
    'assignmentId' : IDL.Text,
    'studentMatric' : IDL.Text,
    'fileIds' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProgressionStage' : IDL.Func([IDL.Text, ProgressionStage], [], []),
    'applyForHostel' : IDL.Func([HostelApplication], [IDL.Text], []),
    'approveRegistration' : IDL.Func([IDL.Text], [], []),
    'approveResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlumniProfile' : IDL.Func([AlumniProfile], [], []),
    'createAnnouncement' : IDL.Func([Announcement], [IDL.Text], []),
    'createAssignment' : IDL.Func([Assignment], [IDL.Text], []),
    'createCAScore' : IDL.Func([CAScore], [IDL.Text], []),
    'createCourse' : IDL.Func([Course], [], []),
    'createDocumentRecord' : IDL.Func([DocumentRecord], [IDL.Text], []),
    'createExamResult' : IDL.Func([ExamResult], [IDL.Text], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Text], []),
    'createMemo' : IDL.Func([Memo], [IDL.Text], []),
    'createProgressionRecord' : IDL.Func([IDL.Text], [], []),
    'createStaff' : IDL.Func([StaffProfile], [], []),
    'createStudent' : IDL.Func([StudentProfile], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
    'dropCourse' : IDL.Func([IDL.Text], [], []),
    'finalizeAppraisal' : IDL.Func([IDL.Text], [], []),
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(CourseRegistration)],
        ['query'],
      ),
    'getAlumniProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AlumniProfile)],
        ['query'],
      ),
    'getAnnouncement' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Announcement)],
        ['query'],
      ),
    'getAppraisal' : IDL.Func([IDL.Text], [IDL.Opt(StaffAppraisal)], ['query']),
    'getCAScore' : IDL.Func([IDL.Text], [IDL.Opt(CAScore)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
    'getDocumentRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DocumentRecord)],
        ['query'],
      ),
    'getExamResult' : IDL.Func([IDL.Text], [IDL.Opt(ExamResult)], ['query']),
    'getHostelApplication' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HostelApplication)],
        ['query'],
      ),
    'getMemo' : IDL.Func([IDL.Text], [IDL.Opt(Memo)], ['query']),
    'getProgressionRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AcademicProgression)],
        ['query'],
      ),
    'getStaff' : IDL.Func([IDL.Text], [IDL.Opt(StaffProfile)], ['query']),
    'getStaffRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StaffRequest)],
        ['query'],
      ),
    'getStudentByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getStudentByMatricNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'gradeSubmission' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'listAllAlumni' : IDL.Func([], [IDL.Vec(AlumniProfile)], ['query']),
    'listAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'listAllAppraisals' : IDL.Func([], [IDL.Vec(StaffAppraisal)], ['query']),
    'listAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'listAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'listAllDocuments' : IDL.Func([], [IDL.Vec(DocumentRecord)], ['query']),
    'listAllHostelApplications' : IDL.Func(
        [],
        [IDL.Vec(HostelApplication)],
        ['query'],
      ),
    'listAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listAllMemos' : IDL.Func([], [IDL.Vec(Memo)], ['query']),
    'listAllProgressionRecords' : IDL.Func(
        [],
        [IDL.Vec(AcademicProgression)],
        ['query'],
      ),
    'listAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'listAllStaffByStaffId' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'listAllStaffRequests' : IDL.Func([], [IDL.Vec(StaffRequest)], ['query']),
    'listAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'listAllStudentsByMatricNumber' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'listAppraisalsByStaff' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StaffAppraisal)],
        ['query'],
      ),
    'listAssignmentsByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'listCAScoresByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CAScore)],
        ['query'],
      ),
    'listCAScoresByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CAScore)],
        ['query'],
      ),
    'listDocumentsByLinkedRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DocumentRecord)],
        ['query'],
      ),
    'listDocumentsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DocumentRecord)],
        ['query'],
      ),
    'listDocumentsByUploader' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DocumentRecord)],
        ['query'],
      ),
    'listHostelApplicationsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HostelApplication)],
        ['query'],
      ),
    'listHostelApplicationsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HostelApplication)],
        ['query'],
      ),
    'listInvoicesByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'listMyStaffRequests' : IDL.Func([], [IDL.Vec(StaffRequest)], ['query']),
    'listMySubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'listRegistrationsByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CourseRegistration)],
        ['query'],
      ),
    'listRegistrationsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CourseRegistration)],
        ['query'],
      ),
    'listResultsByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'listResultsBySemester' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'listResultsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'listResultsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'listSubmissionsByAssignment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'markInvoicePaid' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'processHostelApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'processStaffRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'publishResult' : IDL.Func([IDL.Text], [], []),
    'registerCourse' : IDL.Func([CourseRegistration], [IDL.Text], []),
    'rejectResult' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'reviewAppraisal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssignment' : IDL.Func([Submission], [IDL.Text], []),
    'submitResultForApproval' : IDL.Func([IDL.Text], [], []),
    'submitSelfAppraisal' : IDL.Func([StaffAppraisal], [IDL.Text], []),
    'submitStaffRequest' : IDL.Func([StaffRequest], [IDL.Text], []),
    'updateAlumniProfile' : IDL.Func([IDL.Text, AlumniProfile], [], []),
    'updateAnnouncement' : IDL.Func([IDL.Text, Announcement], [], []),
    'updateCAScore' : IDL.Func([IDL.Text, CAScore], [], []),
    'updateCourse' : IDL.Func([IDL.Text, Course], [], []),
    'updateExamResult' : IDL.Func([IDL.Text, ExamResult], [], []),
    'updateStaff' : IDL.Func([IDL.Text, StaffProfile], [], []),
    'updateStudent' : IDL.Func([IDL.Text, StudentProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };