/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AlumniProfile {
    linkedIn: string;
    matricNumber: string;
    name: string;
    graduationYear: bigint;
    email: string;
    employer: string;
    jobTitle: string;
    department: string;
    location: string;
}
export interface StageRecord {
    decision: string;
    comment: string;
    stage: string;
    decidedAt: bigint;
    decidedBy: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface StaffProfile {
    staffId: string;
    name: string;
    designation: Designation;
    email: string;
    department: string;
}
export interface ProgressionStage {
    status: string;
    completedAt: bigint;
    details: string;
    stageName: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Memo {
    title: string;
    body: string;
    createdAt: bigint;
    targetAudience: string;
    senderName: string;
}
export interface Invoice {
    id: string;
    status: InvoiceStatus;
    semester: string;
    studentMatric: string;
    amount: bigint;
    paidAt?: bigint;
}
export interface StaffAppraisal {
    id: string;
    status: AppraisalStatus;
    staffName: string;
    period: string;
    kpis: string;
    cycle: AppraisalCycle;
    submittedAt: bigint;
    reviewComment?: string;
    reviewerName: string;
    achievements: string;
    selfAppraisalText: string;
    targetsNextPeriod: string;
    staffPrincipal: Principal;
    department: string;
    reviewScore?: string;
}
export interface Course {
    title: string;
    semester: string;
    code: string;
    creditUnits: bigint;
    department: string;
    lecturerId: string;
}
export interface StudentProfile {
    matricNumber: string;
    name: string;
    email: string;
    level: string;
    department: string;
}
export interface StaffRequest {
    id: string;
    status: RequestStatus;
    submittedByName: string;
    createdAt: bigint;
    submittedBy: Principal;
    description: string;
    stageHistory: Array<StageRecord>;
    currentStage: ApprovalStage;
    requestType: RequestType;
}
export interface AcademicProgression {
    stages: Array<ProgressionStage>;
    studentMatric: string;
}
export interface Assignment {
    id: string;
    title: string;
    createdAt: bigint;
    dueDate: bigint;
    description: string;
    createdByLecturerId: string;
    courseCode: string;
}
export interface Submission {
    id: string;
    studentPrincipal: string;
    submittedAt: bigint;
    feedback?: string;
    grade?: string;
    assignmentId: string;
    studentMatric: string;
    fileIds: Array<string>;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppraisalCycle {
    annual = "annual",
    midYear = "midYear"
}
export enum AppraisalStatus {
    submitted = "submitted",
    finalized = "finalized",
    reviewed = "reviewed",
    draft = "draft"
}
export enum ApprovalStage {
    vc = "vc",
    dvc = "dvc",
    hod = "hod",
    dean = "dean"
}
export enum Designation {
    hr = "hr",
    admin = "admin",
    lecturer = "lecturer",
    support = "support",
    bursary = "bursary"
}
export enum InvoiceStatus {
    pending = "pending",
    paid = "paid"
}
export enum RequestStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum RequestType {
    travel = "travel",
    leave = "leave",
    training = "training"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProgressionStage(studentMatric: string, stage: ProgressionStage): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlumniProfile(profile: AlumniProfile): Promise<void>;
    createAssignment(assignment: Assignment): Promise<string>;
    createCourse(course: Course): Promise<void>;
    createInvoice(invoice: Invoice): Promise<string>;
    createMemo(memo: Memo): Promise<string>;
    createProgressionRecord(studentMatric: string): Promise<void>;
    createStaff(staffProfile: StaffProfile): Promise<void>;
    createStudent(student: StudentProfile): Promise<void>;
    finalizeAppraisal(appraisalId: string): Promise<void>;
    getAlumniProfile(matricNumber: string): Promise<AlumniProfile | null>;
    getAppraisal(id: string): Promise<StaffAppraisal | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourse(code: string): Promise<Course | null>;
    getMemo(id: string): Promise<Memo | null>;
    getProgressionRecord(studentMatric: string): Promise<AcademicProgression | null>;
    getStaff(staffId: string): Promise<StaffProfile | null>;
    getStaffRequest(requestId: string): Promise<StaffRequest | null>;
    getStudentByEmail(email: string): Promise<StudentProfile | null>;
    getStudentByMatricNumber(matricNumber: string): Promise<StudentProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    gradeSubmission(submissionId: string, grade: string, feedback: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listAllAlumni(): Promise<Array<AlumniProfile>>;
    listAllAppraisals(): Promise<Array<StaffAppraisal>>;
    listAllAssignments(): Promise<Array<Assignment>>;
    listAllCourses(): Promise<Array<Course>>;
    listAllInvoices(): Promise<Array<Invoice>>;
    listAllMemos(): Promise<Array<Memo>>;
    listAllProgressionRecords(): Promise<Array<AcademicProgression>>;
    listAllStaff(): Promise<Array<StaffProfile>>;
    listAllStaffByStaffId(): Promise<Array<StaffProfile>>;
    listAllStaffRequests(): Promise<Array<StaffRequest>>;
    listAllStudents(): Promise<Array<StudentProfile>>;
    listAllStudentsByMatricNumber(): Promise<Array<StudentProfile>>;
    listAppraisalsByStaff(staffPrincipal: Principal): Promise<Array<StaffAppraisal>>;
    listAssignmentsByCourse(courseCode: string): Promise<Array<Assignment>>;
    listInvoicesByStudent(studentMatric: string): Promise<Array<Invoice>>;
    listMyStaffRequests(): Promise<Array<StaffRequest>>;
    listMySubmissions(studentPrincipal: string): Promise<Array<Submission>>;
    listSubmissionsByAssignment(assignmentId: string): Promise<Array<Submission>>;
    markInvoicePaid(invoiceId: string, paidAt: bigint): Promise<void>;
    processStaffRequest(requestId: string, decision: string, comment: string, decidedBy: string, decidedAt: bigint): Promise<void>;
    reviewAppraisal(appraisalId: string, reviewerName: string, reviewScore: string, reviewComment: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAssignment(submission: Submission): Promise<string>;
    submitSelfAppraisal(appraisal: StaffAppraisal): Promise<string>;
    submitStaffRequest(req: StaffRequest): Promise<string>;
    updateAlumniProfile(matricNumber: string, profile: AlumniProfile): Promise<void>;
    updateCourse(code: string, course: Course): Promise<void>;
    updateStaff(staffId: string, staffProfile: StaffProfile): Promise<void>;
    updateStudent(matricNumber: string, student: StudentProfile): Promise<void>;
}
import type { AcademicProgression as _AcademicProgression, AlumniProfile as _AlumniProfile, AppraisalCycle as _AppraisalCycle, AppraisalStatus as _AppraisalStatus, ApprovalStage as _ApprovalStage, Course as _Course, Designation as _Designation, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, Memo as _Memo, RequestStatus as _RequestStatus, RequestType as _RequestType, StaffAppraisal as _StaffAppraisal, StaffProfile as _StaffProfile, StaffRequest as _StaffRequest, StageRecord as _StageRecord, StudentProfile as _StudentProfile, Submission as _Submission, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProgressionStage(arg0: string, arg1: ProgressionStage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProgressionStage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProgressionStage(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlumniProfile(arg0: AlumniProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlumniProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlumniProfile(arg0);
            return result;
        }
    }
    async createAssignment(arg0: Assignment): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0);
            return result;
        }
    }
    async createCourse(arg0: Course): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0);
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_Invoice_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_Invoice_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMemo(arg0: Memo): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createMemo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMemo(arg0);
            return result;
        }
    }
    async createProgressionRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProgressionRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProgressionRecord(arg0);
            return result;
        }
    }
    async createStaff(arg0: StaffProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(to_candid_StaffProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(to_candid_StaffProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createStudent(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0);
            return result;
        }
    }
    async finalizeAppraisal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeAppraisal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeAppraisal(arg0);
            return result;
        }
    }
    async getAlumniProfile(arg0: string): Promise<AlumniProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlumniProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlumniProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppraisal(arg0: string): Promise<StaffAppraisal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppraisal(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppraisal(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: string): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemo(arg0: string): Promise<Memo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemo(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemo(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressionRecord(arg0: string): Promise<AcademicProgression | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressionRecord(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressionRecord(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaff(arg0: string): Promise<StaffProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffRequest(arg0: string): Promise<StaffRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffRequest(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffRequest(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentByEmail(arg0: string): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentByEmail(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentByEmail(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentByMatricNumber(arg0: string): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentByMatricNumber(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentByMatricNumber(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async gradeSubmission(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.gradeSubmission(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gradeSubmission(arg0, arg1, arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllAlumni(): Promise<Array<AlumniProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllAlumni();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllAlumni();
            return result;
        }
    }
    async listAllAppraisals(): Promise<Array<StaffAppraisal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllAppraisals();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllAppraisals();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllAssignments();
            return result;
        }
    }
    async listAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllCourses();
            return result;
        }
    }
    async listAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllInvoices();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllInvoices();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllMemos(): Promise<Array<Memo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllMemos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllMemos();
            return result;
        }
    }
    async listAllProgressionRecords(): Promise<Array<AcademicProgression>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllProgressionRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllProgressionRecords();
            return result;
        }
    }
    async listAllStaff(): Promise<Array<StaffProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStaff();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStaff();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllStaffByStaffId(): Promise<Array<StaffProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStaffByStaffId();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStaffByStaffId();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllStaffRequests(): Promise<Array<StaffRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStaffRequests();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStaffRequests();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllStudents(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudents();
            return result;
        }
    }
    async listAllStudentsByMatricNumber(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudentsByMatricNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudentsByMatricNumber();
            return result;
        }
    }
    async listAppraisalsByStaff(arg0: Principal): Promise<Array<StaffAppraisal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppraisalsByStaff(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppraisalsByStaff(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssignmentsByCourse(arg0: string): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssignmentsByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssignmentsByCourse(arg0);
            return result;
        }
    }
    async listInvoicesByStudent(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoicesByStudent(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoicesByStudent(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyStaffRequests(): Promise<Array<StaffRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyStaffRequests();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyStaffRequests();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMySubmissions(arg0: string): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMySubmissions(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMySubmissions(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubmissionsByAssignment(arg0: string): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissionsByAssignment(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissionsByAssignment(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async markInvoicePaid(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markInvoicePaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInvoicePaid(arg0, arg1);
            return result;
        }
    }
    async processStaffRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processStaffRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processStaffRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async reviewAppraisal(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewAppraisal(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewAppraisal(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitAssignment(arg0: Submission): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(to_candid_Submission_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(to_candid_Submission_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitSelfAppraisal(arg0: StaffAppraisal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSelfAppraisal(to_candid_StaffAppraisal_n62(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSelfAppraisal(to_candid_StaffAppraisal_n62(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitStaffRequest(arg0: StaffRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitStaffRequest(to_candid_StaffRequest_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitStaffRequest(to_candid_StaffRequest_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAlumniProfile(arg0: string, arg1: AlumniProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlumniProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlumniProfile(arg0, arg1);
            return result;
        }
    }
    async updateCourse(arg0: string, arg1: Course): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1);
            return result;
        }
    }
    async updateStaff(arg0: string, arg1: StaffProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, to_candid_StaffProfile_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, to_candid_StaffProfile_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudent(arg0: string, arg1: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppraisalCycle_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppraisalCycle): AppraisalCycle {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_AppraisalStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppraisalStatus): AppraisalStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStage_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStage): ApprovalStage {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Designation_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Designation): Designation {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_RequestType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestType): RequestType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_StaffAppraisal_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffAppraisal): StaffAppraisal {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_StaffProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffProfile): StaffProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_StaffRequest_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffRequest): StaffRequest {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AlumniProfile]): AlumniProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffAppraisal]): StaffAppraisal | null {
    return value.length === 0 ? null : from_candid_StaffAppraisal_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Memo]): Memo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AcademicProgression]): AcademicProgression | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffProfile]): StaffProfile | null {
    return value.length === 0 ? null : from_candid_StaffProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffRequest]): StaffRequest | null {
    return value.length === 0 ? null : from_candid_StaffRequest_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AppraisalStatus;
    staffName: string;
    period: string;
    kpis: string;
    cycle: _AppraisalCycle;
    submittedAt: bigint;
    reviewComment: [] | [string];
    reviewerName: string;
    achievements: string;
    selfAppraisalText: string;
    targetsNextPeriod: string;
    staffPrincipal: Principal;
    department: string;
    reviewScore: [] | [string];
}): {
    id: string;
    status: AppraisalStatus;
    staffName: string;
    period: string;
    kpis: string;
    cycle: AppraisalCycle;
    submittedAt: bigint;
    reviewComment?: string;
    reviewerName: string;
    achievements: string;
    selfAppraisalText: string;
    targetsNextPeriod: string;
    staffPrincipal: Principal;
    department: string;
    reviewScore?: string;
} {
    return {
        id: value.id,
        status: from_candid_AppraisalStatus_n22(_uploadFile, _downloadFile, value.status),
        staffName: value.staffName,
        period: value.period,
        kpis: value.kpis,
        cycle: from_candid_AppraisalCycle_n24(_uploadFile, _downloadFile, value.cycle),
        submittedAt: value.submittedAt,
        reviewComment: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.reviewComment)),
        reviewerName: value.reviewerName,
        achievements: value.achievements,
        selfAppraisalText: value.selfAppraisalText,
        targetsNextPeriod: value.targetsNextPeriod,
        staffPrincipal: value.staffPrincipal,
        department: value.department,
        reviewScore: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.reviewScore))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffId: string;
    name: string;
    designation: _Designation;
    email: string;
    department: string;
}): {
    staffId: string;
    name: string;
    designation: Designation;
    email: string;
    department: string;
} {
    return {
        staffId: value.staffId,
        name: value.name,
        designation: from_candid_Designation_n36(_uploadFile, _downloadFile, value.designation),
        email: value.email,
        department: value.department
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _RequestStatus;
    submittedByName: string;
    createdAt: bigint;
    submittedBy: Principal;
    description: string;
    stageHistory: Array<_StageRecord>;
    currentStage: _ApprovalStage;
    requestType: _RequestType;
}): {
    id: string;
    status: RequestStatus;
    submittedByName: string;
    createdAt: bigint;
    submittedBy: Principal;
    description: string;
    stageHistory: Array<StageRecord>;
    currentStage: ApprovalStage;
    requestType: RequestType;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n41(_uploadFile, _downloadFile, value.status),
        submittedByName: value.submittedByName,
        createdAt: value.createdAt,
        submittedBy: value.submittedBy,
        description: value.description,
        stageHistory: value.stageHistory,
        currentStage: from_candid_ApprovalStage_n43(_uploadFile, _downloadFile, value.currentStage),
        requestType: from_candid_RequestType_n45(_uploadFile, _downloadFile, value.requestType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _InvoiceStatus;
    semester: string;
    studentMatric: string;
    amount: bigint;
    paidAt: [] | [bigint];
}): {
    id: string;
    status: InvoiceStatus;
    semester: string;
    studentMatric: string;
    amount: bigint;
    paidAt?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n52(_uploadFile, _downloadFile, value.status),
        semester: value.semester,
        studentMatric: value.studentMatric,
        amount: value.amount,
        paidAt: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.paidAt))
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    studentPrincipal: string;
    submittedAt: bigint;
    feedback: [] | [string];
    grade: [] | [string];
    assignmentId: string;
    studentMatric: string;
    fileIds: Array<string>;
}): {
    id: string;
    studentPrincipal: string;
    submittedAt: bigint;
    feedback?: string;
    grade?: string;
    assignmentId: string;
    studentMatric: string;
    fileIds: Array<string>;
} {
    return {
        id: value.id,
        studentPrincipal: value.studentPrincipal,
        submittedAt: value.submittedAt,
        feedback: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.feedback)),
        grade: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.grade)),
        assignmentId: value.assignmentId,
        studentMatric: value.studentMatric,
        fileIds: value.fileIds
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    finalized: null;
} | {
    reviewed: null;
} | {
    draft: null;
}): AppraisalStatus {
    return "submitted" in value ? AppraisalStatus.submitted : "finalized" in value ? AppraisalStatus.finalized : "reviewed" in value ? AppraisalStatus.reviewed : "draft" in value ? AppraisalStatus.draft : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annual: null;
} | {
    midYear: null;
}): AppraisalCycle {
    return "annual" in value ? AppraisalCycle.annual : "midYear" in value ? AppraisalCycle.midYear : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hr: null;
} | {
    admin: null;
} | {
    lecturer: null;
} | {
    support: null;
} | {
    bursary: null;
}): Designation {
    return "hr" in value ? Designation.hr : "admin" in value ? Designation.admin : "lecturer" in value ? Designation.lecturer : "support" in value ? Designation.support : "bursary" in value ? Designation.bursary : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "approved" in value ? RequestStatus.approved : "rejected" in value ? RequestStatus.rejected : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vc: null;
} | {
    dvc: null;
} | {
    hod: null;
} | {
    dean: null;
}): ApprovalStage {
    return "vc" in value ? ApprovalStage.vc : "dvc" in value ? ApprovalStage.dvc : "hod" in value ? ApprovalStage.hod : "dean" in value ? ApprovalStage.dean : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    travel: null;
} | {
    leave: null;
} | {
    training: null;
}): RequestType {
    return "travel" in value ? RequestType.travel : "leave" in value ? RequestType.leave : "training" in value ? RequestType.training : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): InvoiceStatus {
    return "pending" in value ? InvoiceStatus.pending : "paid" in value ? InvoiceStatus.paid : value;
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffAppraisal>): Array<StaffAppraisal> {
    return value.map((x)=>from_candid_StaffAppraisal_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffProfile>): Array<StaffProfile> {
    return value.map((x)=>from_candid_StaffProfile_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffRequest>): Array<StaffRequest> {
    return value.map((x)=>from_candid_StaffRequest_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n58(_uploadFile, _downloadFile, x));
}
function to_candid_AppraisalCycle_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppraisalCycle): _AppraisalCycle {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_AppraisalStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppraisalStatus): _AppraisalStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStage_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStage): _ApprovalStage {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function to_candid_Designation_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Designation): _Designation {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_RequestStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_RequestType_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestType): _RequestType {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_StaffAppraisal_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffAppraisal): _StaffAppraisal {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_StaffProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffProfile): _StaffProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_StaffRequest_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRequest): _StaffRequest {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_Submission_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Submission): _Submission {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: InvoiceStatus;
    semester: string;
    studentMatric: string;
    amount: bigint;
    paidAt?: bigint;
}): {
    id: string;
    status: _InvoiceStatus;
    semester: string;
    studentMatric: string;
    amount: bigint;
    paidAt: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_InvoiceStatus_n12(_uploadFile, _downloadFile, value.status),
        semester: value.semester,
        studentMatric: value.studentMatric,
        amount: value.amount,
        paidAt: value.paidAt ? candid_some(value.paidAt) : candid_none()
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffId: string;
    name: string;
    designation: Designation;
    email: string;
    department: string;
}): {
    staffId: string;
    name: string;
    designation: _Designation;
    email: string;
    department: string;
} {
    return {
        staffId: value.staffId,
        name: value.name,
        designation: to_candid_Designation_n16(_uploadFile, _downloadFile, value.designation),
        email: value.email,
        department: value.department
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    studentPrincipal: string;
    submittedAt: bigint;
    feedback?: string;
    grade?: string;
    assignmentId: string;
    studentMatric: string;
    fileIds: Array<string>;
}): {
    id: string;
    studentPrincipal: string;
    submittedAt: bigint;
    feedback: [] | [string];
    grade: [] | [string];
    assignmentId: string;
    studentMatric: string;
    fileIds: Array<string>;
} {
    return {
        id: value.id,
        studentPrincipal: value.studentPrincipal,
        submittedAt: value.submittedAt,
        feedback: value.feedback ? candid_some(value.feedback) : candid_none(),
        grade: value.grade ? candid_some(value.grade) : candid_none(),
        assignmentId: value.assignmentId,
        studentMatric: value.studentMatric,
        fileIds: value.fileIds
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: AppraisalStatus;
    staffName: string;
    period: string;
    kpis: string;
    cycle: AppraisalCycle;
    submittedAt: bigint;
    reviewComment?: string;
    reviewerName: string;
    achievements: string;
    selfAppraisalText: string;
    targetsNextPeriod: string;
    staffPrincipal: Principal;
    department: string;
    reviewScore?: string;
}): {
    id: string;
    status: _AppraisalStatus;
    staffName: string;
    period: string;
    kpis: string;
    cycle: _AppraisalCycle;
    submittedAt: bigint;
    reviewComment: [] | [string];
    reviewerName: string;
    achievements: string;
    selfAppraisalText: string;
    targetsNextPeriod: string;
    staffPrincipal: Principal;
    department: string;
    reviewScore: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_AppraisalStatus_n64(_uploadFile, _downloadFile, value.status),
        staffName: value.staffName,
        period: value.period,
        kpis: value.kpis,
        cycle: to_candid_AppraisalCycle_n66(_uploadFile, _downloadFile, value.cycle),
        submittedAt: value.submittedAt,
        reviewComment: value.reviewComment ? candid_some(value.reviewComment) : candid_none(),
        reviewerName: value.reviewerName,
        achievements: value.achievements,
        selfAppraisalText: value.selfAppraisalText,
        targetsNextPeriod: value.targetsNextPeriod,
        staffPrincipal: value.staffPrincipal,
        department: value.department,
        reviewScore: value.reviewScore ? candid_some(value.reviewScore) : candid_none()
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: RequestStatus;
    submittedByName: string;
    createdAt: bigint;
    submittedBy: Principal;
    description: string;
    stageHistory: Array<StageRecord>;
    currentStage: ApprovalStage;
    requestType: RequestType;
}): {
    id: string;
    status: _RequestStatus;
    submittedByName: string;
    createdAt: bigint;
    submittedBy: Principal;
    description: string;
    stageHistory: Array<_StageRecord>;
    currentStage: _ApprovalStage;
    requestType: _RequestType;
} {
    return {
        id: value.id,
        status: to_candid_RequestStatus_n70(_uploadFile, _downloadFile, value.status),
        submittedByName: value.submittedByName,
        createdAt: value.createdAt,
        submittedBy: value.submittedBy,
        description: value.description,
        stageHistory: value.stageHistory,
        currentStage: to_candid_ApprovalStage_n72(_uploadFile, _downloadFile, value.currentStage),
        requestType: to_candid_RequestType_n74(_uploadFile, _downloadFile, value.requestType)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    pending: null;
} | {
    paid: null;
} {
    return value == InvoiceStatus.pending ? {
        pending: null
    } : value == InvoiceStatus.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Designation): {
    hr: null;
} | {
    admin: null;
} | {
    lecturer: null;
} | {
    support: null;
} | {
    bursary: null;
} {
    return value == Designation.hr ? {
        hr: null
    } : value == Designation.admin ? {
        admin: null
    } : value == Designation.lecturer ? {
        lecturer: null
    } : value == Designation.support ? {
        support: null
    } : value == Designation.bursary ? {
        bursary: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppraisalStatus): {
    submitted: null;
} | {
    finalized: null;
} | {
    reviewed: null;
} | {
    draft: null;
} {
    return value == AppraisalStatus.submitted ? {
        submitted: null
    } : value == AppraisalStatus.finalized ? {
        finalized: null
    } : value == AppraisalStatus.reviewed ? {
        reviewed: null
    } : value == AppraisalStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppraisalCycle): {
    annual: null;
} | {
    midYear: null;
} {
    return value == AppraisalCycle.annual ? {
        annual: null
    } : value == AppraisalCycle.midYear ? {
        midYear: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == RequestStatus.pending ? {
        pending: null
    } : value == RequestStatus.approved ? {
        approved: null
    } : value == RequestStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStage): {
    vc: null;
} | {
    dvc: null;
} | {
    hod: null;
} | {
    dean: null;
} {
    return value == ApprovalStage.vc ? {
        vc: null
    } : value == ApprovalStage.dvc ? {
        dvc: null
    } : value == ApprovalStage.hod ? {
        hod: null
    } : value == ApprovalStage.dean ? {
        dean: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestType): {
    travel: null;
} | {
    leave: null;
} | {
    training: null;
} {
    return value == RequestType.travel ? {
        travel: null
    } : value == RequestType.leave ? {
        leave: null
    } : value == RequestType.training ? {
        training: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
